### ISSUE TITLE
Rust

### ISSUE THREAD

**Issue by henopiedx** [kronikc/OgarII-CSharp#1]
Hi there!

My name is Henopied, and I am a developer. I also have autism.

I really like that someone is recoding Ogar in C#.

I was wondering if you wanted to work with me to redo it in Rust? I think together we could do it really good, as my autism really helps me with coding, and also my other autistic friend MrSonicMaster can also help!

**Comment by El-Funny-Trollface** [comment]
Haelo guys, i would liek to port thes into 8008 assembly. Also cane we do thes in the javascript or peython. Thanque.

**Comment by kronikc** [comment]
I've never heard of rust. I also am not sure if you are serious or not.
